name: drag_canvas
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  contextmenu: 
  vector_math:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  